# Generated by Django 3.1.7 on 2021-04-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20210428_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Владелец квартиры', 'Владелец квартиры'), ('Директор', 'Директор'), ('Управляющий', 'Управляющий'), ('Бухгалтер', 'Бухгалтер'), ('Электрик', 'Электрик'), ('Сантехник', 'Сантехник')], default=('Владелец квартиры', 'Владелец квартиры'), max_length=150, null=True, verbose_name='role of the user'),
        ),
    ]
