# Generated by Django 3.1.7 on 2021-05-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20210428_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Активен', 'Активен'), ('Новый', 'Новый'), ('Отключен', 'Отключен')], default='Новый', max_length=100, null=True, verbose_name='status of the user'),
        ),
    ]
