# Generated by Django 3.1.7 on 2021-05-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20210502_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=155, verbose_name='ФИО'),
        ),
    ]
