# Generated by Django 3.1.7 on 2021-05-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/users/user_image/', verbose_name='Сменить изображение'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=155, verbose_name='full name'),
        ),
    ]
