# Generated by Django 3.1.7 on 2021-05-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20210510_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='telegram'),
        ),
        migrations.AlterField(
            model_name='user',
            name='viber',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='viber'),
        ),
    ]
