# Generated by Django 3.1.7 on 2021-05-25 15:35

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_auto_20210512_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=25, region=None, verbose_name='phone number'),
        ),
    ]
