version: "3.8"
services:
  web:
    build: .
    container_name: myhome24
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    container_name: postgresdb
    environment:
      - POSTGRES_DB=myhome24_db
      - POSTGRES_USER=artemmint
      - POSTGRES_PASSWORD=12345
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"