version: "3.8"
services:
  web:
    build: .
    container_name: myhome24
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
  pgdb:
    image: postgres:13-alpine
    container_name: postgresdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=pgdb
      - POSTGRES_PORT=5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
volumes:
  pgdata: