from admin_panel.views.invoice import *
from admin_panel.views.users_admin import *
from admin_panel.views.master_request import *
from admin_panel.views.users import *
from admin_panel.views.services_metrics import *
from admin_panel.views.messages import *
from admin_panel.views.flats import *
from admin_panel.views.account_transaction import *
from admin_panel.views.houses import *
from admin_panel.views.manage_site import *
from admin_panel.views.meter_readings import *
from admin_panel.views.pay_company import *
from admin_panel.views.transaction_purpose import *
from admin_panel.views.account import *
from admin_panel.views.statistics_view import *
from admin_panel.views.roles import *
from admin_panel.views.tariffs import *