# Generated by Django 3.1.7 on 2021-05-03 08:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок')),
                ('short_text', ckeditor.fields.RichTextField(max_length=1000, verbose_name='Краткий текст')),
                ('apps_status', models.BooleanField(default='False', verbose_name='Показать ссылки на приложения')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank='', max_length=100, verbose_name='Ед.изм.')),
            ],
        ),
        migrations.CreateModel(
            name='PayCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название компании')),
                ('info', models.TextField(max_length=1500, verbose_name='Информация')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('seo_description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Description')),
                ('seo_keywords', models.CharField(blank=True, max_length=150, null=True, verbose_name='Keywords')),
            ],
        ),
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_page', to='admin_panel.seo', verbose_name='Settings SEO')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicesSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/services_metrics/', verbose_name='Рекомендуемый размер: (650x300)')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание услуги')),
                ('services_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_metrics', to='admin_panel.servicespage', verbose_name='service')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Услуга')),
                ('show_in_meter_reading', models.BooleanField(default='False', verbose_name='Показывать в счетчиках')),
                ('metric', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='admin_panel.metrics', verbose_name='Ед.изм.')),
            ],
        ),
        migrations.CreateModel(
            name='IndexSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/index/slider/', verbose_name='Рекомендуемый размер: (1920x800)')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider', to='admin_panel.indexpage')),
            ],
        ),
        migrations.AddField(
            model_name='indexpage',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_page', to='admin_panel.seo', verbose_name='Settings SEO'),
        ),
        migrations.CreateModel(
            name='IndexBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/index/near_us/', verbose_name='Рекомендуемый размер: (1000x600)')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Заголовок блока')),
                ('description', models.TextField(blank=True, max_length=350, verbose_name='Описание')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='admin_panel.indexpage', verbose_name='Title of the block')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ContactsPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок')),
                ('short_text', ckeditor.fields.RichTextField(blank=True, default='', max_length=1000, verbose_name='Краткий текст')),
                ('url', models.URLField(max_length=500, verbose_name='Ссылка на коммерческий сайт')),
                ('seo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts_page', to='admin_panel.seo', verbose_name='Setting SEO')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactsMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField(default='', max_length=1000, verbose_name='Код карты')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map', to='admin_panel.contactspage', verbose_name='Map')),
            ],
        ),
        migrations.CreateModel(
            name='ContactsAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='ФИО')),
                ('location', models.CharField(blank=True, default='', max_length=100, verbose_name='Локация')),
                ('address', models.CharField(blank=True, default='', max_length=100, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, default='', max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, default='', max_length=100, verbose_name='E-mail')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts_address', to='admin_panel.contactspage', verbose_name='Contacts')),
            ],
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Заголовок')),
                ('short_text', ckeditor.fields.RichTextField(max_length=3000, verbose_name='Краткий текст')),
                ('image', models.ImageField(blank=True, upload_to='images/about/director/', verbose_name='Рекомендуемый размер: (250x310)')),
                ('seo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_page', to='admin_panel.seo', verbose_name='Setting SEO')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/about/gallery/', verbose_name='Рекомендуемый размер: (1200x1200)')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='admin_panel.aboutpage')),
            ],
        ),
        migrations.CreateModel(
            name='AboutExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок')),
                ('short_text', ckeditor.fields.RichTextField(blank=True, max_length=1000, verbose_name='Краткий текст')),
                ('about', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra_info', to='admin_panel.aboutpage')),
            ],
        ),
        migrations.CreateModel(
            name='AboutExtraGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/about/additional_gallery/', verbose_name='Рекомендуемый размер (1200x1200)')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_gallery', to='admin_panel.aboutpage')),
            ],
        ),
        migrations.CreateModel(
            name='AboutDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(blank=True, upload_to='files/about/', verbose_name='PDF, JPG (максимальный размер 20 Mb)')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название документа')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.aboutpage')),
            ],
        ),
    ]
