# Generated by Django 3.1.7 on 2021-05-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_auto_20210503_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='admin_panel.metrics', verbose_name='Ед.изм.'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Услуга'),
        ),
    ]
