# Generated by Django 3.1.7 on 2021-03-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20210322_1308'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IndexBlocks',
            new_name='IndexBlock',
        ),
    ]
