# Generated by Django 3.1.7 on 2021-05-03 09:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20210503_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название тарифа')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание тарифа')),
                ('editing_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TariffService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=500, verbose_name='Цена')),
                ('currency', models.CharField(default='грн', max_length=25, verbose_name='Валюта')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_metrics', to='admin_panel.metrics')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_services', to='admin_panel.services')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_service', to='admin_panel.tariff')),
            ],
        ),
    ]
