# Generated by Django 3.1.7 on 2021-05-03 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_tariff_tariffservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='editing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
