# Generated by Django 3.1.7 on 2021-05-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_auto_20210503_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariff',
            options={'ordering': ['-editing_date']},
        ),
        migrations.AlterField(
            model_name='tariff',
            name='editing_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
