# Generated by Django 3.1.7 on 2021-05-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_auto_20210505_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('type', models.CharField(choices=[('Приход', 'Приход'), ('Расход', 'Расход')], default='Приход', max_length=150, verbose_name='Приход/Расход')),
            ],
        ),
    ]
