# Generated by Django 3.1.7 on 2021-05-08 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_transactionpurpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='show_in_meter_reading',
            field=models.BooleanField(blank=True, default='False', verbose_name='Показывать в счетчиках'),
        ),
        migrations.AlterField(
            model_name='servicessite',
            name='services_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='admin_panel.servicespage', verbose_name='service'),
        ),
    ]
