# Generated by Django 3.1.7 on 2021-03-23 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_auto_20210322_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexblock',
            name='image',
            field=models.ImageField(upload_to='images/index/near_us/', verbose_name='Recommend size (1000x600)'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='admin_panel.seo', verbose_name='Settings SEO'),
        ),
        migrations.AlterField(
            model_name='indexslider',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/index/slider/', verbose_name='Recommend size (1920x800)'),
        ),
        migrations.AlterField(
            model_name='indexslider',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index', to='admin_panel.indexpage'),
        ),
    ]
