# Generated by Django 3.1.7 on 2021-05-08 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_auto_20210508_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(max_length=150, verbose_name='Адрес')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='tariffservice',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_metrics', to='admin_panel.metrics', verbose_name='Ед.изм.'),
        ),
        migrations.AlterField(
            model_name='tariffservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_services', to='admin_panel.services', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='tariffservice',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_service', to='admin_panel.tariff', verbose_name='Тариф'),
        ),
        migrations.CreateModel(
            name='HousePreview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/house/preview/', verbose_name='Изображение')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house', to='admin_panel.house')),
            ],
        ),
    ]
