# Generated by Django 3.1.7 on 2021-05-09 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_auto_20210508_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-editing_date']},
        ),
        migrations.AddField(
            model_name='house',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='editing_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
