# Generated by Django 3.1.7 on 2021-03-24 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_auto_20210323_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexpage',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_page', to='admin_panel.seo', verbose_name='Settings SEO'),
        ),
    ]
