# Generated by Django 3.1.7 on 2021-05-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_auto_20210509_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='house',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='admin_panel.house'),
        ),
        migrations.AddField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='housepreview',
            name='house',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='house_preview', to='admin_panel.house'),
        ),
    ]
