# Generated by Django 3.1.7 on 2021-03-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_auto_20210324_0928'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indexpage',
            old_name='title',
            new_name='main_title',
        ),
    ]
