# Generated by Django 3.1.7 on 2021-03-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_auto_20210324_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexblock',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='indexblock',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/index/near_us/', verbose_name='Recommend size (1000x600)'),
        ),
        migrations.AlterField(
            model_name='indexblock',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
