# Generated by Django 3.1.7 on 2021-05-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_auto_20210509_1927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='HouseSection',
        ),
    ]
