# Generated by Django 3.1.7 on 2021-03-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_auto_20210324_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seo',
            old_name='description',
            new_name='seo_description',
        ),
        migrations.RenameField(
            model_name='seo',
            old_name='keywords',
            new_name='seo_keywords',
        ),
        migrations.RenameField(
            model_name='seo',
            old_name='title',
            new_name='seo_title',
        ),
    ]
