# Generated by Django 3.1.7 on 2021-05-09 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_auto_20210509_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='housesection',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='housesection',
            name='editing_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
