# Generated by Django 3.1.7 on 2021-03-24 10:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_auto_20210324_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutextrainfo',
            name='short_text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='aboutextrainfo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
