# Generated by Django 3.1.7 on 2021-05-10 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_auto_20210509_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housesection',
            name='house',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='house_sections', to='admin_panel.house'),
        ),
    ]
