# Generated by Django 3.1.7 on 2021-05-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_auto_20210510_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housesection',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Название секции'),
        ),
    ]
