# Generated by Django 3.1.7 on 2021-03-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_servicespage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespage',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Service description'),
        ),
        migrations.AlterField(
            model_name='servicespage',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Service name'),
        ),
    ]
