# Generated by Django 3.1.7 on 2021-05-11 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0018_auto_20210510_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Номер этажа')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('editing_date', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='house_floor', to='admin_panel.house')),
            ],
        ),
    ]
