# Generated by Django 3.1.7 on 2021-03-26 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_auto_20210326_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicespage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='servicespage',
            name='name',
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/services/', verbose_name='Recommend size (650x300)')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Service name')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Service description')),
                ('services_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='admin_panel.servicespage', verbose_name='service')),
            ],
        ),
    ]
