# Generated by Django 3.1.7 on 2021-05-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_flat_floor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Floor',
            new_name='HouseFloor',
        ),
    ]
