# Generated by Django 3.1.7 on 2021-05-11 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0020_auto_20210511_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='area',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Площадь(кв.м.)'),
        ),
        migrations.AddField(
            model_name='flat',
            name='floor',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='admin_panel.housefloor'),
        ),
        migrations.AddField(
            model_name='flat',
            name='house',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='admin_panel.house'),
        ),
        migrations.AddField(
            model_name='flat',
            name='number',
            field=models.CharField(max_length=50, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AddField(
            model_name='flat',
            name='owner',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='flats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flat',
            name='section',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='admin_panel.housesection'),
        ),
        migrations.AddField(
            model_name='flat',
            name='tariff',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='admin_panel.tariff'),
        ),
    ]
