# Generated by Django 3.1.7 on 2021-03-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0021_contacts_contactsmap_contactspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsmap',
            name='map',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
