# Generated by Django 3.1.7 on 2021-05-12 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_auto_20210512_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housepreview',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_preview', to='admin_panel.house'),
        ),
        migrations.AlterField(
            model_name='housepreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/house/preview/', verbose_name='Изображение'),
        ),
    ]
