# Generated by Django 3.1.7 on 2021-03-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_auto_20210328_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='ContactsAddress',
        ),
    ]
