# Generated by Django 3.1.7 on 2021-05-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.BigIntegerField(unique=True, verbose_name='№'),
        ),
    ]
