# Generated by Django 3.1.7 on 2021-03-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0025_auto_20210328_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsmap',
            name='map',
            field=models.CharField(default='', max_length=1000, verbose_name='Map code'),
        ),
    ]
