# Generated by Django 3.1.7 on 2021-03-28 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_auto_20210328_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsaddress',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts_address', to='admin_panel.contactspage', verbose_name='Contacts'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='url',
            field=models.URLField(max_length=500, verbose_name='Link on commerce site'),
        ),
    ]
