# Generated by Django 3.1.7 on 2021-03-29 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0027_auto_20210328_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexblock',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='admin_panel.indexpage', verbose_name='Title of the block'),
        ),
    ]
