# Generated by Django 3.1.7 on 2021-03-30 17:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0029_auto_20210329_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactspage',
            name='short_text',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=1000),
        ),
    ]
