# Generated by Django 3.1.7 on 2021-03-30 17:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0030_auto_20210330_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='short_text',
            field=ckeditor.fields.RichTextField(max_length=3000),
        ),
    ]
