# Generated by Django 3.1.7 on 2021-05-21 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_auto_20210521_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='admin_panel.account', verbose_name='Лицевой счет'),
        ),
    ]
