# Generated by Django 3.1.7 on 2021-04-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0031_auto_20210330_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name of company')),
                ('info', models.TextField(max_length=1500, verbose_name='Information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='main_title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
