# Generated by Django 3.1.7 on 2021-04-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0032_auto_20210404_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['-id']},
        ),
    ]
