# Generated by Django 3.1.7 on 2021-05-22 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0032_flat_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(unique=True, verbose_name='№')),
                ('total', models.FloatField(max_length=50, null=True, verbose_name='Сумма')),
                ('confirm', models.BooleanField(default=True, verbose_name='Проведен')),
                ('comment', models.CharField(blank=True, default='', max_length=500, verbose_name='Комментарий')),
                ('type', models.CharField(max_length=50, verbose_name='Приход/расход')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('editing_date', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transactions', to='admin_panel.account', verbose_name='Лицевой счет')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to=settings.AUTH_USER_MODEL, verbose_name='Владелец квартиры')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_transactions', to='admin_panel.transactionpurpose', verbose_name='Статья')),
            ],
            options={
                'ordering': ('-editing_date',),
            },
        ),
    ]
