# Generated by Django 3.1.7 on 2021-04-21 12:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0033_auto_20210404_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indexblock',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='aboutdocument',
            name='document',
            field=models.FileField(upload_to='files/about/', verbose_name='PDF, JPG (максимальный размер 20 Mb)'),
        ),
        migrations.AlterField(
            model_name='aboutdocument',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название документа'),
        ),
        migrations.AlterField(
            model_name='aboutextragallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/about/additional_gallery/', verbose_name='Рекомендуемый размер (1200x1200)'),
        ),
        migrations.AlterField(
            model_name='aboutextrainfo',
            name='short_text',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, verbose_name='Краткий текст'),
        ),
        migrations.AlterField(
            model_name='aboutextrainfo',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='aboutgallery',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/about/gallery/', verbose_name='Рекомендуемый размер: (1200x1200)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image',
            field=models.ImageField(upload_to='images/about/director/', verbose_name='Рекомендуемый размер: (250x310)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='short_text',
            field=ckeditor.fields.RichTextField(max_length=3000, verbose_name='Краткий текст'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='contactsaddress',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contactsaddress',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=100, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contactsaddress',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='contactsaddress',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='contactsaddress',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='contactsmap',
            name='map',
            field=models.CharField(default='', max_length=1000, verbose_name='Код карты'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='short_text',
            field=ckeditor.fields.RichTextField(blank=True, default='', max_length=1000, verbose_name='Краткий текст'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='contactspage',
            name='url',
            field=models.URLField(max_length=500, verbose_name='Ссылка на коммерческий сайт'),
        ),
        migrations.AlterField(
            model_name='indexblock',
            name='description',
            field=models.TextField(blank=True, max_length=350, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='indexblock',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/index/near_us/', verbose_name='Рекомендуемый размер: (1000x600)'),
        ),
        migrations.AlterField(
            model_name='indexblock',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Заголовок блока'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='apps_status',
            field=models.BooleanField(default='False', verbose_name='Показать ссылки на приложения'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='main_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='short_text',
            field=ckeditor.fields.RichTextField(max_length=1000, verbose_name='Краткий текст'),
        ),
        migrations.AlterField(
            model_name='indexslider',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/index/slider/', verbose_name='Рекомендуемый размер: (1920x800)'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='seo_description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='seo_keywords',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Keywords'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='seo_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание услуги'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/services/', verbose_name='Рекомендуемый размер: (650x300)'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название услуги'),
        ),
    ]
