# Generated by Django 3.1.7 on 2021-05-23 18:48

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_panel', '0034_auto_20210522_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='MasterRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True, verbose_name='Время')),
                ('description', models.TextField(blank=True, default='', max_length=1500, verbose_name='Описание')),
                ('master_type', models.CharField(choices=[('Сантехник', 'Сантехник'), ('Электрик', 'Электрик'), ('Слесарь', 'Слесарь'), ('Любой специалист', 'Любой специалист')], default='Любой специалист', max_length=50, verbose_name='Тип мастера')),
                ('status', models.CharField(choices=[('Новое', 'Новое'), ('В работе', 'В работе'), ('Выполнено', 'Выполнено')], default='Новое', max_length=100, verbose_name='Статус')),
                ('comment', ckeditor.fields.RichTextField(blank=True, default='', max_length=500, verbose_name='Комментарий')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('editing_date', models.DateTimeField(auto_now=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_requests', to='admin_panel.flat', verbose_name='Квартира')),
                ('master', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_request_managers', to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_request_owners', to=settings.AUTH_USER_MODEL, verbose_name='Владелец квартиры')),
            ],
            options={
                'ordering': ('-editing_date',),
            },
        ),
    ]
