# Generated by Django 3.1.7 on 2021-04-22 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0034_auto_20210421_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ед.изм.')),
            ],
        ),
        migrations.AlterModelOptions(
            name='services',
            options={},
        ),
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
        migrations.RemoveField(
            model_name='services',
            name='image',
        ),
        migrations.RemoveField(
            model_name='services',
            name='services_page',
        ),
        migrations.AddField(
            model_name='services',
            name='show_in_meter_reading',
            field=models.BooleanField(default='False', verbose_name='Показывать в счетчиках'),
        ),
        migrations.AlterField(
            model_name='paycompany',
            name='info',
            field=models.TextField(max_length=1500, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='paycompany',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Услуга'),
        ),
        migrations.CreateModel(
            name='ServicesSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/services/', verbose_name='Рекомендуемый размер: (650x300)')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='Описание услуги')),
                ('services_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='admin_panel.servicespage', verbose_name='service')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='services',
            name='metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='admin_panel.metrics', verbose_name='Ед.изм.'),
        ),
    ]
