# Generated by Django 3.1.7 on 2021-04-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0035_auto_20210422_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/about/director/', verbose_name='Рекомендуемый размер: (250x310)'),
        ),
    ]
