# Generated by Django 3.1.7 on 2021-05-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0035_auto_20210523_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='№'),
        ),
    ]
