# Generated by Django 3.1.7 on 2021-04-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0036_auto_20210425_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutdocument',
            name='document',
            field=models.FileField(blank=True, upload_to='files/about/', verbose_name='PDF, JPG (максимальный размер 20 Mb)'),
        ),
    ]
