# Generated by Django 3.1.7 on 2021-05-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0037_houseuseradmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housefloor',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер этажа'),
        ),
        migrations.AlterField(
            model_name='housesection',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название секции'),
        ),
        migrations.AlterField(
            model_name='houseuseradmin',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ФИО'),
        ),
    ]
